@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkNkB6Y3ViZS5jby5rciIsImlhdCI6MTY5NTI3ODM3NCwiZXhwIjoxNjk1Mjc4Njc0fQ.5z77sID_zpt_GcC1dzwC5YCOESq8PdnFjog55HTbN-E


###

GET http://{{host}}/users

###
POST http://{{host}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "david6@zcube.co.kr",
    "password" : "1234"
}

###

GET http://{{host}}/auth/profile
Authorization: Bearer {{token}}

###

POST http://{{host}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "david8",
    "password" : "1234",
    "email" : "david8@zcube.co.kr"
}

###

GET http://{{host}}/users/5
Authorization: Bearer {{token}}

###
DELETE http://{{host}}/users/2
Authorization: Bearer {{token}}
